### ISSUE TITLE
How to generate string of specified length for given regular expression?

### ISSUE THREAD

**Issue by yrevar** [leapfrogonline/rstr#1]
Thanks for this cool library. I was wondering if it could generate strings of desired length matching given regular expression.

For instance, I'm looking for following behavior.

```
Input: expression = r'0*1*2', max length=10
Output: a sample of length 10 sequences that matches the regular expression r'0*1*2'
```

**Comment by bjmc** [comment]
I'm glad you're finding it useful! You can specify the number of characters you want using [the `{m}` syntax](https://docs.python.org/3/library/re.html#index-7) in a regular expression. Say, `rstr.xeger('[123]{10}')`.

In your example `r'0*1*2'` the `*` character theoretically matches any number of repetitions between 0 and infinity, but rstr [puts an arbitrary upper bound of 100](https://github.com/leapfrogonline/rstr/blob/master/rstr/xeger.py#L11) on `*` and `+`.

Depending on what you need, you could always just truncate to ten characters, like `rstr.xeger('1*2*3*')[:10]` in order to get a 10-character long string that matches the regex (but you'd usually wind up with all 1s).

If you wanted ten characters with a random mix of those 3 digits, in order, you might do something like `''.join(sorted(rstr.rstr('123', 10)))` but I realize that's not particularly elegant.

**Comment by bjmc** [comment]
@yrevar Was any of the above helpful for you? I'd like to close this issue unless there's an action to take to resolve it. Do you need a different feature beyond what's part of the regular expression syntax or the existing rstr methods?

**Comment by Wolf-at-SO** [comment]
Triggered by this issue, I just installed the package and found out that there is a limit to the `rstr()` method, but nothing comparable for `xeger()`, inother words: the limit doesn't have an effect on the xeger operation.
(maybe the overall idea is to naive, because this is too hard (in a mathematical) sense ... )

Do you plan to implement a limitation?

**Comment by bjmc** [comment]
@Wolf-at-SO The `xeger()` method has a different signature from `rstr()` (and other convenience methods) because all the information about the string you want to generate is encoded within the regular expression itself. If you want to set a limit on the length of a repeat, you can use the syntax `{n,m}` where n is the lower bound and m is the upper bound. For example:

```python
>>> import rstr
>>> rstr.xeger('\d{1,5}')
'1584'
```  
Is that not sufficient for your use case? Can you explain how you would like a `limit` parameter to work for `rstr.xeger()`? What would you hope for it to do?

Regarding your PS, I just tried xeger, and I'm not sure what the purpose of their `limit` parameter is, but it doesn't seem to enforce that limit as a restriction on output length:

```python
>>> from xeger import Xeger
>>> x = Xeger(limit=5)
>>> x.xeger(r'a{10}b{10}')
'aaaaaaaaaabbbbbbbbbb'
>>> len(x.xeger(r'a{10}b{10}'))
20
```

**Comment by Wolf-at-SO** [comment]
> 
> Regarding your PS, I just tried xeger, and I'm not sure what the purpose of their `limit` parameter is, but it doesn't seem to enforce that limit as a restriction on output length:
> 
> ```python
> >>> from xeger import Xeger
> >>> x = Xeger(limit=5)
> >>> x.xeger(r'a{10}b{10}')
> 'aaaaaaaaaabbbbbbbbbb'
> >>> len(x.xeger(r'a{10}b{10}'))
> 20
> ```

Thanks that you point that out. As mentioned in their issue #6, contradicting limit and regex are not handled correctly.

As far as I tried it out, the limit applies on regex that don't exceed the limit, for instance
```
>>> x = Xeger(4)
>>> x.xeger(r'a+')
```

Back to the original issue: 

> Can you explain how you would like a limit parameter to work for rstr.xeger()? What would you hope for it to do?

The problem with encoding limits within the regex itself is that can (by definition) not work on a global scope (i.e. limit the whole output). So length-restricting the output of a `xeger` function would ideally follow some *min/max* logic (defaulting to *0/None*). Such a function would raise an error if the regex itself exceeds the overall restrictions.

**Comment by bjmc** [comment]
The problem I see is that there are a bunch of possible ways to enforce a global limit, and it's not obvious to me why one particular method would be more desirable than any another.

Consider the following:

`rstr.xeger(r'a{1,15}b{5,10}c*', limit=15)`

How should we handle that? The user has requested at least 1 `a` and 5 `b`, and a limit of 15, so we have 9 spare characters to decide "randomly" - but how?

Do we:
- Evaluate from left-to-right, picking `a` first, then `b`, then `c`? (but if we randomly pick 15 `a` then we're hosed because we can't add one `b` and still meet the limit).
- Backtrack and remove one `a` to make room for the `b`? Will we wind up with strings that are more front-heavy? 
- Rewrite the upper bounds before we start? If so, to what? Does the user expect more `a`s or more `b`s on average? We could apply a proportional weighting, something like `new_bound=(15/25) * 15`? 
- Then do we never include any `c` because it's optional? Or based on proportional weighting should our strings be mostly `c`s, since `*` is an "infinite" upper bound? But will that conflict with the fact that we still need 5 `b` and 1 `a`?

Personally, I think it's kind of incoherent to try to impose a global limit on the length of string generated from a regex because the regular expression syntax already gives the user tools to specify exactly what length(s) they want.

If you have some idea of how to implement this, I'm happy to look at a pull request, but I'd expect it to include a justification for why your method of limiting is clearly and obviously better than other possible limiting strategies.

**Comment by bjmc** [comment]
FWIW, Xeger doesn't enforce a global limit, either:

```
>>> from xeger import Xeger
>>> x = Xeger(limit=2)
>>> x.xeger(r'a+b*')
'aabb'
```

It looks like all they're doing is restricting [the upper bound of *each* repeat](https://github.com/crdoconnor/xeger/blob/master/xeger/xeger.py#L134) separately to be no higher than the `limit` parameter. But if a user wanted to have `a{1,2}b{0,2}` then they could have just written that in the first place. Specifying the limit parameter on the `Xeger` class isn't actually buying you anything that I can see.

**Comment by Wolf-at-SO** [comment]
@bjmc Thanks for the response and for the deeper look you had on xeger. The look into the code is now on my todo list. 
I'll think about options for setting up a reasonable feature request ...

**Comment by bjmc** [comment]
I'm gonna close this issue for right now, but I'm happy to look at future pull requests addressing this feature, provided we can come up with a rigorous definition of what the "global" limit should mean.

**Comment by yrevar** [comment]
Thanks, @bjmc. The global limit issue you described in the post above is the exact problem I faced. I needed min and max bound on the occurrence of a set of symbols in time and wanted other symbols to fill up the remaining spots. However, it results in a complicated description and interpretation. I think I'll stick with "rstr.xeger" for now.

The global limit is constrained by upper and lower limits of individual symbols, so it leads to confusing APIs—only some specs are legal and others can't be met. Thinking back about the application, what I needed was fixed size sequences with some symbols spanning random duration and others filling up space. So something like generating unconstrained sequences and then squishing all parts down randomly to the setting that's permissible by the spec. Maybe this is application-specific and needs a more flexible and application restricted description than regex offers.

**Comment by Wolf-at-SO** [comment]
> 
> [...] Maybe this is application-specific and needs a more flexible and application restricted description than regex offers.

Seems you are right. I frequently thought about it and came to the result that extending *regular* expressions with a global limit would end their [regularity in terms of context freedom](https://en.wikipedia.org/wiki/Context-free_language).

**Comment by max-emtelligent** [comment]
I had been using the xeger package's `limit` argument to generate shortest possible matching strings. In my case I really just want to get the minimal length of a match (which shouldn't need to involve generating strings but I wasn't able to find better tools for it). In other cases it seems like getting minimal matching strings could be useful for eg testing edge cases. I'm not able to modify my regexes to use `{n}` since they are intended to match longer strings as well. So I feel like there are real use cases for xeger's limit, when you want to analyze specific cases of regexes which are intended for something more general.

As far as I can see it is easy to implement an equivalent of xeger's `limit` using something like this in `_handle_repeat()`:
```
end_range = min((end_range, max((limit, start_range))))
```

**Comment by bjmc** [comment]
@max-emtelligent Maybe I'm misunderstanding your use case, but it's possible to specify both a minimum and maximum length of a repeat using the regex grammar, `a{2,10}` will produce at least two `a`s and up to ten.

Like I said, I'm not fundamentally opposed to the idea of `limit` for `xeger()` but if you read earlier discussion on this thread, it's not a trivial question to implement a "global" limit in a sensible way.
